export type PastShow = {
  title: string;
  date: string; // ISO 8601
  venue: string;
  city: string;
};

export type Comedian = {
  name: string;
  slug: string;
  tagline: string;
  description: string;
  genre: string[];
  affiliatePath: string;
  photo?: string; // URL — replace with real photo
  instagramPostIds?: string[]; // Replace with real Instagram post IDs from your page
  pastShows?: PastShow[];
};

export type Show = {
  title: string;
  slug: string;
  comedianSlug: string;
  date: string; // ISO 8601
  venue: string;
  city: string;
  affiliatePath: string;
};

export const comedians: Comedian[] = [
  {
    name: "Klaas van der Eerden",
    slug: "klaas-van-der-eerden",
    tagline: "Energieke comedian met fysieke humor",
    description:
      "Klaas van der Eerden staat bekend om zijn energieke stijl, snelle typetjes en fysieke humor. Na een succesvolle periode op televisie keerde hij terug naar het theater met nieuwe cabaretshows.",
    genre: ["Cabaret", "Comedy"],
    affiliatePath: "/klaas-van-der-eerden",
    photo: "/artists/klaas_van_der_eerden.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Karin Bloemen",
    slug: "karin-bloemen",
    tagline: "Cabaretière met krachtige stem en theater flair",
    description:
      "Karin Bloemen is een van de bekendste cabaretières van Nederland. Ze combineert humor met zang en theatrale optredens en staat bekend om haar indrukwekkende kostuums en krachtige stem.",
    genre: ["Cabaret", "Muzikaal"],
    affiliatePath: "/karin-bloemen",
    photo: "/artists/karin_bloemen.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Veldhuis & Kemper",
    slug: "veldhuis-en-kemper",
    tagline: "Cabaretduo met muziek en herkenbare verhalen",
    description:
      "Veldhuis & Kemper vormen een van de populairste cabaretduo’s van Nederland. Hun voorstellingen combineren humor, muziek en herkenbare verhalen over het dagelijks leven.",
    genre: ["Cabaret", "Muzikaal"],
    affiliatePath: "/veldhuis-en-kemper",
    photo: "/artists/veldhuis_kemper.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Martijn Koning",
    slug: "martijn-koning",
    tagline: "Snelle grappen en energieke storytelling",
    description:
      "Martijn Koning staat bekend om zijn snelle humor en energieke vertelstijl. Zijn shows zitten vol onverwachte wendingen en persoonlijke observaties.",
    genre: ["Cabaret", "Stand-up"],
    affiliatePath: "/martijn-koning",
    photo: "/artists/martijn_koning.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Bert Visscher",
    slug: "bert-visscher",
    tagline: "Theatraal cabaret met spectaculaire humor",
    description:
      "Bert Visscher is een van de meest theatrale cabaretiers van Nederland. Zijn shows staan bekend om de energieke stijl, grote decors en fysieke comedy.",
    genre: ["Cabaret"],
    affiliatePath: "/bert-visscher",
    photo: "/artists/bert_visscher.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Roue Verveer",
    slug: "roue-verveer",
    tagline: "Publieksfavoriet met scherpe observaties",
    description:
      "Roué Verveer staat bekend om zijn energieke stand-up en scherpe observaties over cultuur en het dagelijks leven.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/roue-verveer",
    photo: "/artists/roue_verveer.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Henry van Loon",
    slug: "henry-van-loon",
    tagline: "Absurdistische cabaretier met unieke stijl",
    description:
      "Henry van Loon combineert absurdistische humor met persoonlijke verhalen. Zijn optredens zijn energiek, eigenzinnig en vaak verrassend.",
    genre: ["Cabaret"],
    affiliatePath: "/henry-van-loon",
    photo: "/artists/henry_van_loon.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Sara Kroos",
    slug: "sara-kroos",
    tagline: "Persoonlijk en muzikaal cabaret",
    description:
      "Sara Kroos staat bekend om haar persoonlijke cabaretshows waarin humor, muziek en openhartige verhalen samenkomen.",
    genre: ["Cabaret", "Muzikaal"],
    affiliatePath: "/sara-kroos",
    photo: "/artists/sara_kroos.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Alex Ploeg",
    slug: "alex-ploeg",
    tagline: "Donkere humor met scherpe randjes",
    description:
      "Alex Ploeg is een cabaretier en stand-up comedian die bekendstaat om zijn scherpe, soms donkere humor en originele invalshoeken.",
    genre: ["Cabaret", "Stand-up"],
    affiliatePath: "/alex-ploeg",
    photo: "/artists/alex_ploeg.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Tineke Schouten",
    slug: "tineke-schouten",
    tagline: "Grande dame van het Nederlandse cabaret",
    description:
      "Tineke Schouten is al decennialang een vaste waarde in het Nederlandse cabaret. Met typetjes, zang en humor weet ze volle theaters te vermaken.",
    genre: ["Cabaret", "Entertainment"],
    affiliatePath: "/tineke-schouten",
    photo: "/artists/tineke_schouten.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Jandino Asporaat",
    slug: "jandino-asporaat",
    tagline: "Energieke entertainer en comedian",
    description:
      "Jandino Asporaat is een populaire comedian en entertainer. Zijn shows combineren stand-up comedy, verhalen en interactie met het publiek.",
    genre: ["Comedy", "Cabaret"],
    affiliatePath: "/jandino-asporaat",
    photo: "/artists/jandino_asporaat.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Kor Hoebe",
    slug: "kor-hoebe",
    tagline: "Nieuwe generatie stand-up comedy",
    description:
      "Kor Hoebe behoort tot de nieuwe generatie Nederlandse comedians en staat bekend om zijn snelle, directe humor.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/kor-hoebe",
    photo: "/artists/kor_hoebe.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Patrick Laureij",
    slug: "patrick-laureij",
    tagline: "Rotterdamse stand-up met scherpe humor",
    description:
      "Patrick Laureij brak door met zijn rauwe Rotterdamse humor en scherpe observaties. Zijn shows zitten vol persoonlijke verhalen en harde grappen.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/patrick-laureij",
    photo: "/artists/patrick_laureij.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Daniel Arends",
    slug: "daniel-arends",
    tagline: "Scherp en compromisloos cabaret",
    description:
      "Daniel Arends staat bekend om zijn compromisloze humor en intense optredens. Hij wordt gezien als een van de meest originele cabaretiers van Nederland.",
    genre: ["Cabaret", "Stand-up"],
    affiliatePath: "/daniel-arends",
    photo: "/artists/daniel_arends.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Tim Fransen",
    slug: "tim-fransen",
    tagline: "Filosofisch cabaret met inhoud",
    description:
      "Tim Fransen combineert filosofie met cabaret. Zijn voorstellingen zijn grappig én intellectueel en zetten het publiek aan het denken.",
    genre: ["Cabaret"],
    affiliatePath: "/tim-fransen",
    photo: "/artists/tim_fransen.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Eric van Sauers",
    slug: "eric-van-sauers",
    tagline: "Veteran van het Nederlandse cabaret",
    description:
      "Eric van Sauers staat bekend om zijn energieke speelstijl en sterke verhalen. Hij behoort al jarenlang tot de vaste namen in het cabaret.",
    genre: ["Cabaret"],
    affiliatePath: "/eric-van-sauers",
    photo: "/artists/eric_van_sauers.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Fred van Leer",
    slug: "fred-van-leer",
    tagline: "Entertainment met humor en persoonlijkheid",
    description:
      "Fred van Leer brengt een mix van humor, persoonlijke verhalen en entertainment naar het theater.",
    genre: ["Entertainment", "Comedy"],
    affiliatePath: "/fred-van-leer",
    photo: "/artists/fred_van_leer.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Alex Klaasen",
    slug: "alex-klaasen",
    tagline: "Cabaret, musical en comedy gecombineerd",
    description:
      "Alex Klaasen combineert cabaret met musical en theater. Zijn shows staan bekend om creativiteit, zang en humor.",
    genre: ["Cabaret", "Musical"],
    affiliatePath: "/alex-klaasen",
    photo: "/artists/alex_klaasen.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Rayen Panday",
    slug: "rayen-panday",
    tagline: "Stand-up comedy met scherpe observaties",
    description:
      "Rayen Panday staat bekend om zijn snelle humor en scherpe observaties over het dagelijks leven.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/rayen-panday",
    photo: "/artists/rayen_panday.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Claudia de Breij",
    slug: "claudia-de-breij",
    tagline: "Muzikaal cabaret met scherpe humor",
    description:
      "Claudia de Breij combineert cabaret met muziek en maatschappelijk commentaar. Ze behoort tot de bekendste cabaretières van Nederland.",
    genre: ["Cabaret", "Muzikaal"],
    affiliatePath: "/claudia-de-breij",
    photo: "/artists/claudia_de_breij.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Najib Amhali",
    slug: "najib-amhali",
    tagline: "Internationaal bekende Nederlandse comedian",
    description:
      "Najib Amhali is een van de populairste comedians van Nederland. Zijn shows combineren snelle humor met persoonlijke verhalen.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/najib-amhali",
    photo: "/artists/najib_amhali.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Brigitte Kaandorp",
    slug: "brigitte-kaandorp",
    tagline: "Cabaret met muziek en absurdistische humor",
    description:
      "Brigitte Kaandorp staat bekend om haar unieke mix van muziek, humor en absurdisme. Ze is een icoon in het Nederlandse cabaret.",
    genre: ["Cabaret", "Muzikaal"],
    affiliatePath: "/brigitte-kaandorp",
    photo: "/artists/brigitte_kaandorp.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Hans Teeuwen",
    slug: "hans-teeuwen",
    tagline: "Provocerende pionier van absurd cabaret",
    description:
      "Hans Teeuwen is een van de meest invloedrijke cabaretiers van Nederland. Zijn absurde en provocerende stijl maakte hem internationaal bekend.",
    genre: ["Cabaret", "Stand-up"],
    affiliatePath: "/hans-teeuwen",
    photo: "/artists/hans_teeuwen.jpg",
    instagramPostIds: [],
    pastShows: [],
  },
  {
    name: "Guido Weijers",
    slug: "guido-weijers",
    tagline: "Energieke stand-up comedian",
    description:
      "Guido Weijers staat bekend om zijn snelle grappen, improvisatie en interactie met het publiek.",
    genre: ["Stand-up", "Cabaret"],
    affiliatePath: "/guido-weijers",
    photo: "/artists/guido_weijers.jpg",
    instagramPostIds: [],
    pastShows: [],
  }
];

export const shows: Show[] = [
  // Klaas van der Eerden – Blijven drijven (meerdere data in 2025)
  {
    title: "Klaas van der Eerden – Blijven drijven",
    slug: "klaas-van-der-eerden-blijven-drijven-schiedam",
    comedianSlug: "klaas-van-der-eerden",
    date: "2025-09-17T20:15:00",
    venue: "Theater Aan De Schie",
    city: "Schiedam",
    affiliatePath: "/klaas-van-der-eerden",
  },
  {
    title: "Klaas van der Eerden – Blijven drijven",
    slug: "klaas-van-der-eerden-blijven-drijven-amstelveen",
    comedianSlug: "klaas-van-der-eerden",
    date: "2025-09-18T20:00:00",
    venue: "Schouwburg Amstelveen",
    city: "Amstelveen",
    affiliatePath: "/klaas-van-der-eerden",
  },
  {
    title: "Klaas van der Eerden – Blijven drijven",
    slug: "klaas-van-der-eerden-blijven-drijven-venray",
    comedianSlug: "klaas-van-der-eerden",
    date: "2025-09-24T20:15:00",
    venue: "Schouwburg Venray",
    city: "Venray",
    affiliatePath: "/klaas-van-der-eerden",
  },

  // Karin Bloemen – Renaissance 2.0 (diverse data voorjaar 2026)
  {
    title: "Karin Bloemen – Renaissance 2.0",
    slug: "karin-bloemen-renaissance-2-0-helmond",
    comedianSlug: "karin-bloemen",
    date: "2026-03-06T20:15:00",
    venue: "Theater T Speelhuis",
    city: "Helmond",
    affiliatePath: "/karin-bloemen",
  },
  {
    title: "Karin Bloemen – Renaissance 2.0",
    slug: "karin-bloemen-renaissance-2-0-rijswijk",
    comedianSlug: "karin-bloemen",
    date: "2026-05-08T20:00:00",
    venue: "De Rijswijkse Schouwburg",
    city: "Rijswijk",
    affiliatePath: "/karin-bloemen",
  },
  {
    title: "Karin Bloemen – Renaissance 2.0",
    slug: "karin-bloemen-renaissance-2-0-papendrecht",
    comedianSlug: "karin-bloemen",
    date: "2026-04-18T20:15:00",
    venue: "Theater De Willem",
    city: "Papendrecht",
    affiliatePath: "/karin-bloemen",
  },
  {
    title: "Karin Bloemen – Renaissance 2.0",
    slug: "karin-bloemen-renaissance-2-0-almere",
    comedianSlug: "karin-bloemen",
    date: "2026-05-09T20:15:00",
    venue: "Kunstlinie Almere Flevoland",
    city: "Almere",
    affiliatePath: "/karin-bloemen",
  },
  {
    title: "Karin Bloemen – Renaissance 2.0",
    slug: "karin-bloemen-renaissance-2-0-apeldoorn",
    comedianSlug: "karin-bloemen",
    date: "2026-04-24T20:00:00",
    venue: "Orpheus",
    city: "Apeldoorn",
    affiliatePath: "/karin-bloemen",
  },

  // Veldhuis & Kemper – Kunnen het niet laten (algemene tourdata 2026)
  {
    title: "Veldhuis & Kemper – Kunnen het niet laten",
    slug: "veldhuis-en-kemper-kunnen-het-niet-laten-delft",
    comedianSlug: "veldhuis-en-kemper",
    date: "2026-03-03T20:15:00",
    venue: "Theater de Veste",
    city: "Delft",
    affiliatePath: "/veldhuis-en-kemper",
  },
  {
    title: "Veldhuis & Kemper – Kunnen het niet laten",
    slug: "veldhuis-en-kemper-kunnen-het-niet-laten-emmen",
    comedianSlug: "veldhuis-en-kemper",
    date: "2026-03-06T20:00:00",
    venue: "ATLAS Theater",
    city: "Emmen",
    affiliatePath: "/veldhuis-en-kemper",
  },
  {
    title: "Veldhuis & Kemper – Kunnen het niet laten",
    slug: "veldhuis-en-kemper-kunnen-het-niet-laten-veenendaal",
    comedianSlug: "veldhuis-en-kemper",
    date: "2026-04-03T20:00:00",
    venue: "Theater Lampegiet",
    city: "Veenendaal",
    affiliatePath: "/veldhuis-en-kemper",
  }, // Martijn Koning – shows 2026 (TopTicketshop vermeldt o.a.)
  {
    title: "Martijn Koning – Een aap die geen bananen eet",
    slug: "martijn-koning-een-aap-die-geen-bananen-eet-waalwijk",
    comedianSlug: "martijn-koning",
    date: "2026-03-04T20:00:00",
    venue: "Theater De Leest",
    city: "Waalwijk",
    affiliatePath: "/martijn-koning",
  },
  {
    title: "Martijn Koning – Een aap die geen bananen eet",
    slug: "martijn-koning-een-aap-die-geen-bananen-eet-emmeloord",
    comedianSlug: "martijn-koning",
    date: "2026-03-05T20:00:00",
    venue: "Theater T Voorhuys",
    city: "Emmeloord",
    affiliatePath: "/martijn-koning",
  },

  // Bert Visscher – shows 2026 (voor zover data beschikbaar)
  {
    title: "Bert Visscher – Cabaretvoorstelling",
    slug: "bert-visscher-cabaretvoorstelling-papendrecht",
    comedianSlug: "bert-visscher",
    date: "2026-01-17T20:00:00",
    venue: "Theater De Willem",
    city: "Papendrecht",
    affiliatePath: "/bert-visscher",
  },
  {
    title: "Bert Visscher – Cabaretvoorstelling",
    slug: "bert-visscher-cabaretvoorstelling-winterswijk",
    comedianSlug: "bert-visscher",
    date: "2026-02-12T20:00:00",
    venue: "Theater De Storm",
    city: "Winterswijk",
    affiliatePath: "/bert-visscher",
  },
  {
    title: "Bert Visscher – Cabaretvoorstelling",
    slug: "bert-visscher-cabaretvoorstelling-nieuwegein",
    comedianSlug: "bert-visscher",
    date: "2026-03-17T20:00:00",
    venue: "De Kom",
    city: "Nieuwegein",
    affiliatePath: "/bert-visscher",
  },

  // Roué Verveer – Op eigen risico shows 2026
  {
    title: "Roué Verveer – Op eigen risico",
    slug: "roue-verveer-op-eigen-risico-breda",
    comedianSlug: "roue-verveer",
    date: "2026-02-10T20:30:00",
    venue: "Chassé Theater",
    city: "Breda",
    affiliatePath: "/roue-verveer",
  },
  {
    title: "Roué Verveer – Op eigen risico",
    slug: "roue-verveer-op-eigen-risico-tilburg",
    comedianSlug: "roue-verveer",
    date: "2026-02-11T20:15:00",
    venue: "Theaters Tilburg",
    city: "Tilburg",
    affiliatePath: "/roue-verveer",
  },
  {
    title: "Roué Verveer – Op eigen risico",
    slug: "roue-verveer-op-eigen-risico-sneek",
    comedianSlug: "roue-verveer",
    date: "2026-02-12T20:15:00",
    venue: "Theater Sneek",
    city: "Sneek",
    affiliatePath: "/roue-verveer",
  },
  {
    title: "Roué Verveer – Op eigen risico",
    slug: "roue-verveer-op-eigen-risico-beverwijk",
    comedianSlug: "roue-verveer",
    date: "2026-02-13T20:15:00",
    venue: "Kennemer Theater",
    city: "Beverwijk",
    affiliatePath: "/roue-verveer",
  },
  {
    title: "Roué Verveer – Op eigen risico",
    slug: "roue-verveer-op-eigen-risico-den-haag",
    comedianSlug: "roue-verveer",
    date: "2026-02-26T20:00:00",
    venue: "Koninklijke Schouwburg",
    city: "Den Haag",
    affiliatePath: "/roue-verveer",
  },
  // Henry van Loon – Keanu (rode Luxor‑serie shows)
  {
    title: "Henry van Loon – Keanu",
    slug: "henry-van-loon-keanu-oud-luxor-rotterdam-15-april",
    comedianSlug: "henry-van-loon",
    date: "2026-04-15T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/henry-van-loon",
  },
  {
    title: "Henry van Loon – Keanu",
    slug: "henry-van-loon-keanu-oud-luxor-rotterdam-16-april",
    comedianSlug: "henry-van-loon",
    date: "2026-04-16T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/henry-van-loon",
  },
  {
    title: "Henry van Loon – Keanu",
    slug: "henry-van-loon-keanu-oud-luxor-rotterdam-17-april",
    comedianSlug: "henry-van-loon",
    date: "2026-04-17T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/henry-van-loon",
  },
  {
    title: "Henry van Loon – Keanu",
    slug: "henry-van-loon-keanu-oud-luxor-rotterdam-18-april",
    comedianSlug: "henry-van-loon",
    date: "2026-04-18T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/henry-van-loon",
  },

  // Sara Kroos – Prikkelarme kermis
  {
    title: "Sara Kroos – Prikkelarme kermis",
    slug: "sara-kroos-prikkelarme-kermis-oude-luxor-rotterdam-20-maart",
    comedianSlug: "sara-kroos",
    date: "2026-03-20T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/sara-kroos",
  },
  {
    title: "Sara Kroos – Prikkelarme kermis",
    slug: "sara-kroos-prikkelarme-kermis-oude-luxor-rotterdam-21-maart",
    comedianSlug: "sara-kroos",
    date: "2026-03-21T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/sara-kroos",
  },
  {
    title: "Sara Kroos – Prikkelarme kermis",
    slug: "sara-kroos-prikkelarme-kermis-zaantheater-10-april",
    comedianSlug: "sara-kroos",
    date: "2026-04-10T20:00:00",
    venue: "Zaantheater",
    city: "Zaandam",
    affiliatePath: "/sara-kroos",
  },

  // Alex Ploeg – Unplugged series
  {
    title: "Alex Ploeg – Unplugged",
    slug: "alex-ploeg-unplugged-theater-orpheus-27-mrt",
    comedianSlug: "alex-ploeg",
    date: "2026-03-27T20:00:00",
    venue: "Theater Orpheus",
    city: "Apeldoorn",
    affiliatePath: "/alex-ploeg",
  },
  {
    title: "Alex Ploeg – Unplugged",
    slug: "alex-ploeg-unplugged-schouwburg-concertzaal-tilburg-26-mrt",
    comedianSlug: "alex-ploeg",
    date: "2026-03-26T20:15:00",
    venue: "Schouwburg Concertzaal Tilburg",
    city: "Tilburg",
    affiliatePath: "/alex-ploeg",
  },
  {
    title: "Alex Ploeg – Unplugged",
    slug: "alex-ploeg-unplugged-oude-luxor-rotterdam-28-mrt",
    comedianSlug: "alex-ploeg",
    date: "2026-03-28T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/alex-ploeg",
  },
  {
    title: "Alex Ploeg – Unplugged",
    slug: "alex-ploeg-unplugged-theateraandeparade-den-bosch-03-mrt",
    comedianSlug: "alex-ploeg",
    date: "2026-03-03T20:00:00",
    venue: "Theater aan de Parade",
    city: "Den Bosch",
    affiliatePath: "/alex-ploeg",
  },
  {
    title: "Alex Ploeg – Unplugged",
    slug: "alex-ploeg-unplugged-flint-zaal-25-jan",
    comedianSlug: "alex-ploeg",
    date: "2026-01-25T20:15:00",
    venue: "AFAS Theaterzaal (Flint)",
    city: "Amersfoort",
    affiliatePath: "/alex-ploeg",
  }, // Tineke Schouten – Femme Vitaal 2026
  {
    title: "Tineke Schouten – Femme Vitaal",
    slug: "tineke-schouten-femme-vitaal-alkmaar",
    comedianSlug: "tineke-schouten",
    date: "2026-01-10T20:15:00",
    venue: "Theater De Vest",
    city: "Alkmaar",
    affiliatePath: "/tineke-schouten",
  },
  {
    title: "Tineke Schouten – Femme Vitaal",
    slug: "tineke-schouten-femme-vitaal-enschede",
    comedianSlug: "tineke-schouten",
    date: "2026-03-05T20:00:00",
    venue: "Wilminktheater",
    city: "Enschede",
    affiliatePath: "/tineke-schouten",
  },
  {
    title: "Tineke Schouten – Femme Vitaal",
    slug: "tineke-schouten-femme-vitaal-bergen-op-zoom",
    comedianSlug: "tineke-schouten",
    date: "2026-03-06T20:00:00",
    venue: "Theater De Maagd",
    city: "Bergen op Zoom",
    affiliatePath: "/tineke-schouten",
  },
  {
    title: "Tineke Schouten – Femme Vitaal",
    slug: "tineke-schouten-femme-vitaal-zaandam",
    comedianSlug: "tineke-schouten",
    date: "2026-04-21T20:00:00",
    venue: "Zaantheater",
    city: "Zaandam",
    affiliatePath: "/tineke-schouten",
  },
  {
    title: "Tineke Schouten – Femme Vitaal",
    slug: "tineke-schouten-femme-vitaal-rotterdam",
    comedianSlug: "tineke-schouten",
    date: "2026-05-22T20:00:00",
    venue: "Nieuwe Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/tineke-schouten",
  },

  // Jandino Asporaat – Omdat je lult! 2026
  {
    title: "Jandino Asporaat – Omdat je lult!",
    slug: "jandino-asporaat-omdat-je-lult-schiedam",
    comedianSlug: "jandino-asporaat",
    date: "2026-01-23T20:15:00",
    venue: "Theater aan de Schie",
    city: "Schiedam",
    affiliatePath: "/jandino-asporaat",
  },
  {
    title: "Jandino Asporaat – Omdat je lult!",
    slug: "jandino-asporaat-omdat-je-lult-zwolle",
    comedianSlug: "jandino-asporaat",
    date: "2026-01-27T20:00:00",
    venue: "Theater de Spiegel",
    city: "Zwolle",
    affiliatePath: "/jandino-asporaat",
  },
  {
    title: "Jandino Asporaat – Omdat je lult!",
    slug: "jandino-asporaat-omdat-je-lult-rotterdam",
    comedianSlug: "jandino-asporaat",
    date: "2026-03-01T20:00:00",
    venue: "Theater Zuidplein",
    city: "Rotterdam",
    affiliatePath: "/jandino-asporaat",
  },
  {
    title: "Jandino Asporaat – Omdat je lult!",
    slug: "jandino-asporaat-omdat-je-lult-sneek",
    comedianSlug: "jandino-asporaat",
    date: "2026-03-19T20:15:00",
    venue: "Theater Sneek",
    city: "Sneek",
    affiliatePath: "/jandino-asporaat",
  },
  {
    title: "Jandino Asporaat – Omdat je lult!",
    slug: "jandino-asporaat-omdat-je-lult-hengelo",
    comedianSlug: "jandino-asporaat",
    date: "2026-03-16T20:00:00",
    venue: "Schouwburg Hengelo",
    city: "Hengelo",
    affiliatePath: "/jandino-asporaat",
  },

  // Kor Hoebe – Kordaat 2026
  {
    title: "Kor Hoebe – Kordaat",
    slug: "kor-hoebe-kordaat-theater-orpheus-apeldoorn",
    comedianSlug: "kor-hoebe",
    date: "2026-01-17T20:00:00",
    venue: "Theater Orpheus",
    city: "Apeldoorn",
    affiliatePath: "/kor-hoebe",
  },
  {
    title: "Kor Hoebe – Kordaat",
    slug: "kor-hoebe-kordaat-tilburg",
    comedianSlug: "kor-hoebe",
    date: "2026-03-07T20:00:00",
    venue: "Toon Hermans Theater",
    city: "Sittard",
    affiliatePath: "/kor-hoebe",
  },
  {
    title: "Kor Hoebe – Kordaat",
    slug: "kor-hoebe-kordaat-theater-heerlen",
    comedianSlug: "kor-hoebe",
    date: "2026-03-19T20:00:00",
    venue: "Theater Heerlen",
    city: "Heerlen",
    affiliatePath: "/kor-hoebe",
  },
  {
    title: "Kor Hoebe – Kordaat",
    slug: "kor-hoebe-kordaat-rotterdam-24-jun",
    comedianSlug: "kor-hoebe",
    date: "2026-06-24T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/kor-hoebe",
  },
  {
    title: "Kor Hoebe – Kordaat",
    slug: "kor-hoebe-kordaat-bergen-op-zoom",
    comedianSlug: "kor-hoebe",
    date: "2026-06-17T20:00:00",
    venue: "Theater De Maagd",
    city: "Bergen op Zoom",
    affiliatePath: "/kor-hoebe",
  },
  // Patrick Laureij – Kintsugi
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-16-jan-rotterdam",
    comedianSlug: "patrick-laureij",
    date: "2026-01-16T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/patrick-laureij",
  },
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-17-jan-rotterdam",
    comedianSlug: "patrick-laureij",
    date: "2026-01-17T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/patrick-laureij",
  },
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-03-mar-rotterdam",
    comedianSlug: "patrick-laureij",
    date: "2026-03-03T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/patrick-laureij",
  },
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-26-may-rotterdam",
    comedianSlug: "patrick-laureij",
    date: "2026-05-26T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/patrick-laureij",
  },
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-05-jun-terneuzen",
    comedianSlug: "patrick-laureij",
    date: "2026-06-05T20:00:00",
    venue: "Scheldetheater",
    city: "Terneuzen",
    affiliatePath: "/patrick-laureij",
  },
  {
    title: "Patrick Laureij – Kintsugi",
    slug: "patrick-laureij-kintsugi-19-may-almere",
    comedianSlug: "patrick-laureij",
    date: "2026-05-19T20:15:00",
    venue: "Kunstlinie",
    city: "Almere",
    affiliatePath: "/patrick-laureij",
  },

  // Daniel Arends – diverse shows 2026
  {
    title: "Daniel Arends – High Class Bitch",
    slug: "daniel-arends-high-class-bitch-30-jan-zaandam",
    comedianSlug: "daniel-arends",
    date: "2026-01-30T20:00:00",
    venue: "Zaantheater",
    city: "Zaandam",
    affiliatePath: "/daniel-arends",
  },
  {
    title: "Daniel Arends – High Class Bitch",
    slug: "daniel-arends-high-class-bitch-26-mar-deventer",
    comedianSlug: "daniel-arends",
    date: "2026-03-26T20:00:00",
    venue: "Deventer Schouwburg",
    city: "Deventer",
    affiliatePath: "/daniel-arends",
  },
  {
    title: "Daniel Arends – High Class Bitch",
    slug: "daniel-arends-high-class-bitch-10-apr-maastricht",
    comedianSlug: "daniel-arends",
    date: "2026-04-10T20:00:00",
    venue: "Theater Aan Het Vrijthof",
    city: "Maastricht",
    affiliatePath: "/daniel-arends",
  },

  // Tim Fransen – Onbekommerd / diverse theaters 2026
  {
    title: "Tim Fransen – Onbekommerd",
    slug: "tim-fransen-onbekommerd-amsterdam-16-jan",
    comedianSlug: "tim-fransen",
    date: "2026-01-16T20:15:00",
    venue: "Meervaart",
    city: "Amsterdam",
    affiliatePath: "/tim-fransen",
  },
  {
    title: "Tim Fransen – Onbekommerd",
    slug: "tim-fransen-onbekommerd-maastricht-22-jan",
    comedianSlug: "tim-fransen",
    date: "2026-01-22T20:00:00",
    venue: "Theater aan het Vrijthof",
    city: "Maastricht",
    affiliatePath: "/tim-fransen",
  },
  {
    title: "Tim Fransen – Onbekommerd",
    slug: "tim-fransen-onbekommerd-rotterdam-01-apr",
    comedianSlug: "tim-fransen",
    date: "2026-04-01T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/tim-fransen",
  },
  {
    title: "Tim Fransen – Onbekommerd",
    slug: "tim-fransen-onbekommerd-sneek-04-apr",
    comedianSlug: "tim-fransen",
    date: "2026-04-04T20:15:00",
    venue: "Stichting Cultuur Kwartier",
    city: "Sneek",
    affiliatePath: "/tim-fransen",
  },
  {
    title: "Tim Fransen – Onbekommerd",
    slug: "tim-fransen-onbekommerd-belgië-12-apr",
    comedianSlug: "tim-fransen",
    date: "2026-04-12T20:00:00",
    venue: "Kennemer Theater",
    city: "Beverwijk",
    affiliatePath: "/tim-fransen",
  },
  // Eric van Sauers – #UNMUTE 2026
  {
    title: "Eric van Sauers – #UNMUTE",
    slug: "eric-van-sauers-unmute-16-jan-alkmaar",
    comedianSlug: "eric-van-sauers",
    date: "2026-01-16T20:15:00",
    venue: "Theater De Vest",
    city: "Alkmaar",
    affiliatePath: "/eric-van-sauers",
  },
  {
    title: "Eric van Sauers – #UNMUTE",
    slug: "eric-van-sauers-unmute-21-feb-nieuwegein",
    comedianSlug: "eric-van-sauers",
    date: "2026-02-21T20:15:00",
    venue: "De Kom",
    city: "Nieuwegein",
    affiliatePath: "/eric-van-sauers",
  },
  {
    title: "Eric van Sauers – #UNMUTE",
    slug: "eric-van-sauers-unmute-20-feb-amersfoort",
    comedianSlug: "eric-van-sauers",
    date: "2026-02-20T20:15:00",
    venue: "Flint",
    city: "Amersfoort",
    affiliatePath: "/eric-van-sauers",
  },
  {
    title: "Eric van Sauers – #UNMUTE",
    slug: "eric-van-sauers-unmute-27-mrt-utrecht",
    comedianSlug: "eric-van-sauers",
    date: "2026-03-27T20:00:00",
    venue: "Stadsschouwburg Utrecht",
    city: "Utrecht",
    affiliatePath: "/eric-van-sauers",
  },
  {
    title: "Eric van Sauers – #UNMUTE",
    slug: "eric-van-sauers-unmute-13-mrt-zaandam",
    comedianSlug: "eric-van-sauers",
    date: "2026-03-13T20:30:00",
    venue: "Zaantheater",
    city: "Zaandam",
    affiliatePath: "/eric-van-sauers",
  },

  // Fred van Leer – cabaret/theater 2026
  {
    title: "Fred van Leer – Ik weet het eigenlijk niet",
    slug: "fred-van-leer-ik-weet-het-eigenlijk-niet-bussum",
    comedianSlug: "fred-van-leer",
    date: "2026-04-30T20:00:00",
    venue: "Spant",
    city: "Bussum",
    affiliatePath: "/fred-van-leer",
  },

  // Alex Klaasen – Stoornis of my Life 2026
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-28-mrt-venlo",
    comedianSlug: "alex-klaasen",
    date: "2026-03-28T20:15:00",
    venue: "Maaspoort",
    city: "Venlo",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-29-mrt-venlo",
    comedianSlug: "alex-klaasen",
    date: "2026-03-29T20:15:00",
    venue: "Maaspoort",
    city: "Venlo",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-10-apr-amsterdam",
    comedianSlug: "alex-klaasen",
    date: "2026-04-10T20:15:00",
    venue: "Meervaart",
    city: "Amsterdam",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-11-apr-amsterdam",
    comedianSlug: "alex-klaasen",
    date: "2026-04-11T20:15:00",
    venue: "Meervaart",
    city: "Amsterdam",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-15-jun-amersfoort",
    comedianSlug: "alex-klaasen",
    date: "2026-06-15T20:15:00",
    venue: "Flint",
    city: "Amersfoort",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-17-jun-rotterdam",
    comedianSlug: "alex-klaasen",
    date: "2026-06-17T20:00:00",
    venue: "Nieuwe Luxortheater",
    city: "Rotterdam",
    affiliatePath: "/alex-klaasen",
  },
  {
    title: "Alex Klaasen – Stoornis of my Life",
    slug: "alex-klaasen-stoornis-of-my-life-01-jul-zwolle",
    comedianSlug: "alex-klaasen",
    date: "2026-07-01T20:00:00",
    venue: "De Spiegel",
    city: "Zwolle",
    affiliatePath: "/alex-klaasen",
  },
  // Rayen Panday – Grip (2026)
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-03-apr-rotterdam",
    comedianSlug: "rayen-panday",
    date: "2026-04-03T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-04-apr-rotterdam",
    comedianSlug: "rayen-panday",
    date: "2026-04-04T20:00:00",
    venue: "Oude Luxor Theater",
    city: "Rotterdam",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-09-apr-barneveld",
    comedianSlug: "rayen-panday",
    date: "2026-04-09T20:00:00",
    venue: "Schaffelaartheater",
    city: "Barneveld",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-07-may-den-bosch",
    comedianSlug: "rayen-panday",
    date: "2026-05-07T20:00:00",
    venue: "Theater aan de Parade",
    city: "Den Bosch",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-15-may-bredda",
    comedianSlug: "rayen-panday",
    date: "2026-05-15T20:15:00",
    venue: "De Meerpaal",
    city: "Dronten",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-21-may-bergen-op-zoom",
    comedianSlug: "rayen-panday",
    date: "2026-05-21T20:00:00",
    venue: "Stadsschouwburg De Maagd",
    city: "Bergen op Zoom",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-27-may-amsterdam",
    comedianSlug: "rayen-panday",
    date: "2026-05-27T20:15:00",
    venue: "De Kleine Komedie",
    city: "Amsterdam",
    affiliatePath: "/rayen-panday",
  },
  {
    title: "Rayen Panday – Grip",
    slug: "rayen-panday-grip-28-may-amsterdam",
    comedianSlug: "rayen-panday",
    date: "2026-05-28T20:15:00",
    venue: "De Kleine Komedie",
    city: "Amsterdam",
    affiliatePath: "/rayen-panday",
  },

  // Claudia de Breij – Een Hoop bandtour (2026)
  {
    title: "Claudia de Breij & band – Een Hoop",
    slug: "claudia-de-breij-een-hoop-utrecht-12-jan",
    comedianSlug: "claudia-de-breij",
    date: "2026-01-12T20:00:00",
    venue: "Musis Sacrum",
    city: "Arnhem",
    affiliatePath: "/claudia-de-breij",
  },
  {
    title: "Claudia de Breij & band – Een Hoop",
    slug: "claudia-de-breij-een-hoop-utrecht-19-jan",
    comedianSlug: "claudia-de-breij",
    date: "2026-01-19T20:00:00",
    venue: "TivoliVredenburg",
    city: "Utrecht",
    affiliatePath: "/claudia-de-breij",
  },
  {
    title: "Claudia de Breij & band – Een Hoop",
    slug: "claudia-de-breij-een-hoop-nijmegen-28-jan",
    comedianSlug: "claudia-de-breij",
    date: "2026-01-28T20:15:00",
    venue: "De Vereeniging",
    city: "Nijmegen",
    affiliatePath: "/claudia-de-breij",
  },
  {
    title: "Claudia de Breij & band – Een Hoop",
    slug: "claudia-de-breij-een-hoop-amsterdam-14-jan",
    comedianSlug: "claudia-de-breij",
    date: "2026-01-14T20:15:00",
    venue: "Het Concertgebouw",
    city: "Amsterdam",
    affiliatePath: "/claudia-de-breij",
  },
  // Brigitte Kaandorp – geen shows beschikbaar 2026
  {
    title: "Brigitte Kaandorp – Geen geplande shows in 2026",
    slug: "brigitte-kaandorp-geen-shows-2026",
    comedianSlug: "brigitte-kaandorp",
    date: "",
    venue: "",
    city: "",
    affiliatePath: "/brigitte-kaandorp",
  },

  // Hans Teeuwen – De Laffe Verlosser (bekende data 2026)
  {
    title: "Hans Teeuwen – De Laffe Verlosser",
    slug: "hans-teeuwen-de-laffe-verlosser-utrecht-24-feb",
    comedianSlug: "hans-teeuwen",
    date: "2026-02-24T20:00:00",
    venue: "Beatrix Theater",
    city: "Utrecht",
    affiliatePath: "/hans-teeuwen",
  },
  {
    title: "Hans Teeuwen – De Laffe Verlosser",
    slug: "hans-teeuwen-de-laffe-verlosser-den-haag-06-mar",
    comedianSlug: "hans-teeuwen",
    date: "2026-03-06T20:00:00",
    venue: "World Forum Theater",
    city: "Den Haag",
    affiliatePath: "/hans-teeuwen",
  },
  {
    title: "Hans Teeuwen – De Laffe Verlosser",
    slug: "hans-teeuwen-de-laffe-verlosser-antwerpen-11-jun",
    comedianSlug: "hans-teeuwen",
    date: "2026-06-11T20:00:00",
    venue: "Stadsschouwburg",
    city: "Antwerpen",
    affiliatePath: "/hans-teeuwen",
  },
  {
    title: "Hans Teeuwen – De Laffe Verlosser",
    slug: "hans-teeuwen-de-laffe-verlosser-amsterdam-26-jun",
    comedianSlug: "hans-teeuwen",
    date: "2026-06-26T20:00:00",
    venue: "AFAS Live",
    city: "Amsterdam",
    affiliatePath: "/hans-teeuwen",
  },

  // Guido Weijers – Oudejaarsconference 2026
  {
    title: "Guido Weijers – Oudejaarsconference 2026",
    slug: "guido-weijers-oudejaarsconference-03-dec-breda",
    comedianSlug: "guido-weijers",
    date: "2026-12-03T20:00:00",
    venue: "Chassé Theater",
    city: "Breda",
    affiliatePath: "/guido-weijers",
  },
  {
    title: "Guido Weijers – Oudejaarsconference 2026",
    slug: "guido-weijers-oudejaarsconference-07-nov-tilburg",
    comedianSlug: "guido-weijers",
    date: "2026-11-07T20:15:00",
    venue: "Schouwburg Concertzaal Tilburg",
    city: "Tilburg",
    affiliatePath: "/guido-weijers",
  },
  {
    title: "Guido Weijers – Oudejaarsconference 2026",
    slug: "guido-weijers-oudejaarsconference-14-nov-den-bosch",
    comedianSlug: "guido-weijers",
    date: "2026-11-14T20:00:00",
    venue: "Brabanthallen",
    city: "'s-Hertogenbosch",
    affiliatePath: "/guido-weijers",
  },
  {
    title: "Guido Weijers – Oudejaarsconference 2026",
    slug: "guido-weijers-oudejaarsconference-06-dec-maastricht",
    comedianSlug: "guido-weijers",
    date: "2026-12-06T20:00:00",
    venue: "Theater aan het Vrijthof",
    city: "Maastricht",
    affiliatePath: "/guido-weijers",
  },
  {
    title: "Guido Weijers – Oudejaarsconference 2026",
    slug: "guido-weijers-oudejaarsconference-23-dec-amsterdam",
    comedianSlug: "guido-weijers",
    date: "2026-12-23T20:00:00",
    venue: "AFAS Live",
    city: "Amsterdam",
    affiliatePath: "/guido-weijers",
  }
];

export function getComedian(slug: string): Comedian | undefined {
  return comedians.find((c) => c.slug === slug);
}

export function getShow(slug: string): Show | undefined {
  return shows.find((s) => s.slug === slug);
}

export function getShowsForComedian(comedianSlug: string): Show[] {
  return shows.filter((s) => s.comedianSlug === comedianSlug);
}

export function getRelatedComedians(currentSlug: string, count = 3): Comedian[] {
  return comedians.filter((c) => c.slug !== currentSlug).slice(0, count);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("nl-NL", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function formatDateShort(iso: string): string {
  return new Date(iso).toLocaleDateString("nl-NL", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString("nl-NL", {
    hour: "2-digit",
    minute: "2-digit",
  });
}
